import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('physical PostgreSQL ER model: composite FK, indexes, SQL, persistence and graphic exports', async ({ page }) => {
  test.setTimeout(60000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Новый проект', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: /ERD/ }).click()
  await expect(page.getByRole('tab', { name: /ERD/ })).toBeVisible()
  const table = async (name: string) => {
    await page.getByRole('button', { name: '＋ Таблица', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Структура таблицы' })
    await dialog.getByLabel('Имя таблицы', { exact: true }).fill(name)
    return dialog
  }
  const parent = await table('accounts')
  await parent.getByLabel('Комментарий таблицы').fill('Счета клиентов')
  await parent.getByRole('button', { name: '＋ Колонка', exact: true }).click()
  const tenant = parent.locator('.er-column-edit').nth(1)
  await tenant.getByLabel('Имя колонки').fill('tenant_id')
  await tenant.getByLabel('Тип данных').selectOption('bigint')
  await tenant.getByLabel('Первичный ключ').check()
  await parent.getByRole('button', { name: 'Применить структуру' }).click()

  const child = await table('orders')
  for (const name of ['account_id', 'tenant_id', 'amount', 'payload']) {
    await child.getByRole('button', { name: '＋ Колонка', exact: true }).click()
    const row = child.locator('.er-column-edit').last()
    await row.getByLabel('Имя колонки').fill(name)
    await row.getByLabel('Тип данных').selectOption(name === 'amount' ? 'numeric' : name === 'payload' ? 'jsonb' : 'bigint')
    if (name !== 'payload') await row.getByLabel('Разрешён NULL').uncheck()
    if (name === 'amount') {
      await row.getByLabel('Параметры типа').fill('12,2')
      await row.locator('summary').click()
      await row.getByLabel('DEFAULT (SQL)').fill('0')
    }
  }
  await child.getByRole('button', { name: '＋ Индекс / UNIQUE' }).click()
  const index = child.locator('.er-constraint-edit').last()
  await index.getByLabel('Имя индекса / ограничения').fill('orders_account_idx')
  await index.getByRole('group', { name: /Ключевые колонки/ }).getByLabel('account_id').check()
  await index.getByRole('group', { name: /Ключевые колонки/ }).getByLabel('tenant_id').check()
  await child.getByRole('button', { name: '＋ CHECK' }).click()
  await child.getByLabel('Имя CHECK').fill('positive_amount')
  await child.getByLabel('Выражение CHECK').fill('amount >= 0')
  await child.getByRole('button', { name: 'Применить структуру' }).click()

  // Position both tables through normal canvas dragging.
  const bounds = await page.locator('.canvas-area').boundingBox()
  if (!bounds) throw new Error('Missing canvas')
  for (const [name, x, y] of [['accounts', 10, 60], ['orders', 510, 160]] as const) {
    const header = page.locator('.er-table-node').filter({ has: page.locator('header strong', { hasText: name }) }).locator('header')
    const box = await header.boundingBox()
    if (!box) throw new Error('Missing table')
    await page.mouse.move(box.x + 30, box.y + 18)
    await page.mouse.down()
    await page.mouse.move(bounds.x + x + 30, bounds.y + y + 18, { steps: 15 })
    await page.mouse.up()
  }
  await page.getByRole('button', { name: '＋ Внешний ключ' }).click()
  const fk = page.getByRole('dialog', { name: 'Внешний ключ', exact: true })
  await fk.getByLabel('Имя ограничения').fill('orders_account_fk')
  await fk.getByLabel('Таблица с внешним ключом').selectOption({ label: 'public.orders' })
  await fk.getByLabel('Родительская таблица').selectOption({ label: 'public.accounts' })
  await fk.getByLabel('Колонка FK 1', { exact: true }).selectOption({ label: 'account_id' })
  await fk.getByLabel('Колонка PK/UNIQUE 1', { exact: true }).selectOption({ label: 'id' })
  await fk.getByRole('button', { name: '＋ Пара колонок' }).click()
  await fk.getByLabel('Колонка FK 2', { exact: true }).selectOption({ label: 'tenant_id' })
  await fk.getByLabel('Колонка PK/UNIQUE 2', { exact: true }).selectOption({ label: 'tenant_id' })
  await fk.getByLabel('ON DELETE').selectOption('CASCADE')
  await fk.getByLabel('DEFERRABLE', { exact: true }).check()
  await fk.getByLabel('INITIALLY DEFERRED').check()
  await fk.getByRole('button', { name: 'Применить связь' }).click()
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  await expect(page.locator('.er-key-badges .fk')).toHaveCount(2)
  await expect(page.getByRole('complementary', { name: 'Свойства ERD' })).toContainText('ON DELETE CASCADE')
  await expect(page.locator('.problems-toggle')).toContainText('0 ошибок')
  await expect(page.locator('.problems-toggle')).toContainText('0 предупреждений')
  await page.screenshot({ path: 'test-results/er-editor.png', fullPage: true })
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'SQL PostgreSQL 18' }).click()
  const file = await download
  await file.saveAs('test-results/schema.sql')
  const sql = await readFile('test-results/schema.sql', 'utf8')
  expect(sql).toContain('numeric(12,2) DEFAULT 0 NOT NULL')
  expect(sql).toContain('FOREIGN KEY ("account_id", "tenant_id")')
  expect(sql).toContain('ON DELETE CASCADE')
  expect(sql).toContain('DEFERRABLE INITIALLY DEFERRED')
  for (const [label, ext] of [['Векторный SVG', 'svg'], ['Изображение PNG', 'png'], ['Все диаграммы в PDF', 'pdf']] as const) {
    await page.locator('.export-menu summary').click()
    const exportFile = page.waitForEvent('download')
    await page.getByRole('button', { name: label, exact: true }).click()
    await (await exportFile).saveAs(`test-results/er-export.${ext}`)
    await page.locator('.export-menu summary').click()
  }
  await expect(page.locator('.project-heading [role=status]')).toHaveText('Сохранено в браузере')
  await page.reload()
  await page.locator('.project-card-open').first().click()
  await expect(page.locator('.er-table-node')).toHaveCount(2)
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  await expect(page.locator('.er-key-badges .fk')).toHaveCount(2)
  await page.getByRole('button', { name: 'Структура orders', exact: true }).click()
  await page.getByRole('dialog').locator('.er-column-edit').nth(1).getByRole('button', { name: 'Удалить колонку' }).click()
  await page.getByRole('button', { name: 'Применить структуру' }).click()
  await expect(page.locator('.react-flow__edge')).toHaveCount(0)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  expect(errors).toEqual([])
})

test('column handles create a relationship and mixed diagrams remain independent', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Новый проект', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: /IDEF0/ }).click()
  await page.getByRole('button', { name: 'Добавить диаграмму', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: /ERD/ }).click()
  for (const name of ['parent', 'child']) {
    await page.getByRole('button', { name: '＋ Таблица', exact: true }).click()
    await page.getByRole('dialog').getByLabel('Имя таблицы', { exact: true }).fill(name)
    await page.getByRole('button', { name: 'Применить структуру' }).click()
  }
  const bounds = await page.locator('.canvas-area').boundingBox()
  if (!bounds) throw new Error('Missing canvas')
  const first = page.locator('.er-table-node').first(), second = page.locator('.er-table-node').last()
  for (const [node, x] of [[first, 10], [second, 490]] as const) {
    const box = await node.boundingBox()
    if (!box) throw new Error('Missing table')
    await page.mouse.move(box.x + 30, box.y + 18)
    await page.mouse.down()
    await page.mouse.move(bounds.x + x + 30, bounds.y + 120, { steps: 12 })
    await page.mouse.up()
  }
  const from = await second.locator('.react-flow__handle-left').first().boundingBox()
  const to = await first.locator('.react-flow__handle-right').first().boundingBox()
  if (!from || !to) throw new Error('Missing handles')
  await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
  await page.mouse.down()
  await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 15 })
  await page.mouse.up()
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  await expect(page.locator('.er-inspector')).toContainText('Кратность: 0..1 → 1')
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(page.locator('.react-flow__edge')).toHaveCount(0)
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  await page.getByRole('tab', { name: /IDEF0/ }).click()
  await page.getByRole('button', { name: 'Создать контекстную диаграмму' }).click()
  await expect(page.locator('.react-flow__node-idef0Function')).toHaveCount(1)
  await page.getByRole('tab', { name: /ERD/ }).click()
  await expect(page.locator('.er-table-node')).toHaveCount(2)
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  expect(errors).toEqual([])
})
