import { test, expect } from '@playwright/test'

test('flowchart editing, transitions, mixed projects, persistence and exports', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Новый проект', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: /Блок-схема/ }).click()
  await expect(page.getByRole('tab', { name: /Блок-схема/ })).toBeVisible()
  const canvas = await page.locator('.canvas-area').boundingBox()
  if (!canvas) throw new Error('Missing canvas')
  for (const [shape, title, text, x, y] of [
    ['start', 'Начало', 'Начало', 120, 30],
    ['process', 'Процесс', 'Получить число', 100, 160],
    ['decision', 'Условие', 'Число > 0?', 390, 130],
    ['end', 'Конец', 'Конец', 420, 350],
  ] as const) {
    await page.getByRole('button', { name: `＋ ${title}`, exact: true }).click()
    const node = page.locator(`.shape-${shape}`)
    const input = node.getByRole('textbox')
    await expect(input).toHaveValue('')
    await input.fill(text)
    await input.press('Tab')
    const box = await node.boundingBox()
    if (!box) throw new Error('Missing node')
    await page.mouse.move(box.x + box.width * 0.25, box.y + 7)
    await page.mouse.down()
    await page.mouse.move(canvas.x + x + box.width * 0.25, canvas.y + y + 7, { steps: 12 })
    await page.mouse.up()
  }
  const connect = async (source: string, sourceSide: string, target: string, targetSide: string) => {
    const from = await page.locator(`.shape-${source} [data-handleid="${sourceSide}"]`).boundingBox()
    const to = await page.locator(`.shape-${target} [data-handleid="${targetSide}"]`).boundingBox()
    if (!from || !to) throw new Error('Missing handles')
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
    await page.mouse.down()
    await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 15 })
    await page.mouse.up()
  }
  await connect('start', 'bottom', 'process', 'top')
  await connect('process', 'right', 'decision', 'left')
  await connect('decision', 'bottom', 'end', 'top')
  await expect(page.locator('.react-flow__edge')).toHaveCount(3)
  await page.getByRole('textbox', { name: 'Подпись', exact: true }).fill('Да')
  await page.getByRole('textbox', { name: 'Подпись', exact: true }).press('Enter')
  await connect('decision', 'top', 'process', 'top')
  await page.getByRole('textbox', { name: 'Подпись', exact: true }).fill('Нет')
  await page.getByRole('textbox', { name: 'Подпись', exact: true }).press('Enter')
  await expect(page.locator('.react-flow__edge')).toHaveCount(4)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(page.locator('.react-flow__edge')).toHaveCount(3)
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.locator('.react-flow__edge')).toHaveCount(4)
  await page.screenshot({ path: 'test-results/flowchart-editor.png', fullPage: true })
  await page.getByRole('button', { name: 'Добавить диаграмму', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: /IDEF0/ }).click()
  await page.getByRole('button', { name: 'Создать контекстную диаграмму' }).click()
  await expect(page.locator('.react-flow__node-idef0Function')).toHaveCount(1)
  await page.getByRole('tab', { name: /Блок-схема/ }).click()
  await expect(page.locator('.react-flow__node-flowchart')).toHaveCount(4)
  await expect(page.locator('.project-heading [role=status]')).toHaveText('Сохранено в браузере')
  for (const [label, extension] of [['Векторный SVG', 'svg'], ['Изображение PNG', 'png'], ['Все диаграммы в PDF', 'pdf']] as const) {
    await page.locator('summary').click()
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name: label, exact: true }).click()
    await (await download).saveAs(`test-results/flowchart.${extension}`)
    await page.locator('summary').click()
  }
  await page.reload()
  await page.locator('.project-card-open').first().click()
  await expect(page.locator('.react-flow__node-flowchart')).toHaveCount(4)
  await expect(page.locator('.shape-process textarea')).toHaveValue('Получить число')
  await expect(page.locator('.react-flow__edge')).toHaveCount(4)
  expect(errors).toEqual([])
})

test('adding a flowchart to IDEF0 and changing shapes retains text and history', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Новый проект', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: /IDEF0/ }).click()
  await page.getByRole('button', { name: 'Добавить диаграмму', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: /Блок-схема/ }).click()
  await page.getByRole('button', { name: '＋ Ввод / вывод', exact: true }).click()
  const input = page.locator('.shape-inputOutput textarea')
  await input.fill('Вывести результат')
  await input.press('Tab')
  await page.getByRole('combobox', { name: 'Фигура' }).selectOption('subprocess')
  await expect(page.locator('.shape-subprocess textarea')).toHaveValue('Вывести результат')
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(page.locator('.shape-inputOutput textarea')).toHaveValue('Вывести результат')
  await page.getByRole('button', { name: '＋ Подпроцесс', exact: true }).click()
  await page.getByRole('button', { name: 'Копия', exact: true }).click()
  await expect(page.locator('.react-flow__node-flowchart')).toHaveCount(3)
  await page.getByRole('button', { name: 'Удалить', exact: true }).click()
  await expect(page.locator('.react-flow__node-flowchart')).toHaveCount(2)
  await page.getByRole('tab', { name: /IDEF0/ }).click()
  await page.getByRole('button', { name: 'Создать контекстную диаграмму' }).click()
  await expect(page.locator('.react-flow__node-idef0Function')).toHaveCount(1)
  expect(errors).toEqual([])
})
