import 'fake-indexeddb/auto'
import { mkdirSync, writeFileSync } from 'node:fs'
import { beforeEach, expect, it } from 'vitest'
import { createEmptyProject } from '@/features/project/lib/projectFactory'
import { parseProjectJson, serializeProject } from '@/features/project/lib/projectFile'
import { useIdef0Store } from '@/features/diagram/model/useIdef0Store'
import { buildDiagramSvg } from '@/features/export/lib/exportDiagram'
import { saveProjectToStorage, listStoredProjects } from '@/features/project/lib/projectStorage'
import { newColumn, newForeignKey, erTables, erHandle, relationshipCardinality, tableHeight } from './model'
import { buildPostgresSQL } from './sql'
import { validateER } from './validateER'
import { formatDataType, typeError } from './postgresTypes'

const store = () => useIdef0Store.getState()
const diagram = () => store().project.diagrams.find(d => d.id === store().currentDiagramId)!
beforeEach(() => { store().setProject(createEmptyProject('er')) })

function setup() {
  store().addERTable({ x: 0, y: 0 })
  const parent = structuredClone(erTables(diagram())[0]!)
  parent.table.columns.push({ ...newColumn('tenant_id'), dataType: 'bigint', primaryKey: true, nullable: false })
  parent.table.columns.push({ ...newColumn('balance'), dataType: 'numeric', typeArgs: '12,2', defaultValue: '0', nullable: false })
  parent.table.checks.push({ id: 'check-positive', name: 'positive_balance', expression: 'balance >= 0' })
  store().updateERTable(parent.id, 'accounts', parent.table, 'Клиенты банка')
  store().addERTable({ x: 550, y: 100 })
  const child = structuredClone(erTables(diagram())[1]!)
  child.table.columns.push({ ...newColumn('account_id'), dataType: 'bigint', nullable: false }, { ...newColumn('tenant_id'), dataType: 'bigint', nullable: false })
  const fk = { ...newForeignKey(child.table.columns[1]!.id, parent.table.columns[0]!.id), columns: child.table.columns.slice(1).map(c => c.id), referencedColumns: parent.table.columns.slice(0, 2).map(c => c.id), onDelete: 'CASCADE' as const }
  child.table.indexes.push({ id: 'idx-fk', name: 'transfers_account_idx', kind: 'index', method: 'btree', columns: [...fk.columns], include: [], unique: false, nullsNotDistinct: false, predicate: '' })
  store().updateERTable(child.id, 'transfers', child.table, '')
  expect(store().saveERForeignKey(null, child.id, parent.id, 'transfers_account_fk', fk)).toBe(true)
  return { parent, child, fk }
}

it('roundtrips physical metadata through JSON and IndexedDB, preserving prior formats', async () => {
  setup()
  expect(validateER(diagram())).toEqual([])
  expect(parseProjectJson(serializeProject(store().project))).toEqual(store().project)
  await saveProjectToStorage(store().project)
  expect((await listStoredProjects()).find(p => p.id === store().project.id)).toEqual(store().project)
  const legacy = createEmptyProject('idef0')
  legacy.version = '3.0.0'
  expect(parseProjectJson(serializeProject(legacy)).version).toBe('4.0.0')
})

it('exports composite constraints in dependency order and renders column metadata', () => {
  setup()
  const sql = buildPostgresSQL(diagram())
  expect(sql).toContain('PRIMARY KEY ("id", "tenant_id")')
  expect(sql).toContain('"balance" numeric(12,2) DEFAULT 0 NOT NULL')
  expect(sql).toContain('GENERATED BY DEFAULT AS IDENTITY')
  expect(sql).toContain('FOREIGN KEY ("account_id", "tenant_id") REFERENCES "public"."accounts" ("id", "tenant_id") MATCH SIMPLE ON DELETE CASCADE')
  expect(sql.indexOf('CREATE INDEX')).toBeLessThan(sql.indexOf('ALTER TABLE'))
  const svg = buildDiagramSvg(diagram()).svg
  expect(svg).toContain('numeric(12,2)')
  expect(svg).toContain('NOT NULL')
  expect(svg).toContain('0..N')
  expect(svg).toContain('positive_balance')
})

it('deletes affected FKs with a column atomically, restores them with undo and remaps copied graphs', () => {
  const { parent, child } = setup()
  const previous = store().project
  const changed = structuredClone(erTables(diagram())[0]!)
  changed.table.columns.shift()
  store().updateERTable(changed.id, changed.name, changed.table, '')
  expect(diagram().arrows).toHaveLength(0)
  store().undo()
  expect(store().project).toBe(previous)
  store().setSelection({ nodeIds: [parent.id, child.id], arrowIds: [] })
  store().duplicateSelection()
  expect(erTables(diagram())).toHaveLength(4)
  expect(diagram().arrows).toHaveLength(2)
  expect(parseProjectJson(serializeProject(store().project))).toEqual(store().project)
  expect(validateER(diagram()).filter(i => i.severity === 'error')).toEqual([])
  expect(new Set(erTables(diagram()).flatMap(n => n.table.columns.map(c => c.id))).size).toBe(12)
})

it('supports self references and derives cardinality from uniqueness and nullability', () => {
  store().addERTable({ x: 0, y: 0 })
  const n = structuredClone(erTables(diagram())[0]!)
  const manager = { ...newColumn('manager_id'), dataType: 'bigint', unique: true }
  n.table.columns.push(manager)
  store().updateERTable(n.id, 'staff', n.table, '')
  const id = n.table.columns[0]!.id
  expect(store().connectArrow({ source: n.id, target: n.id, sourceHandle: erHandle(manager.id, 'right'), targetHandle: erHandle(id, 'left') }).ok).toBe(true)
  expect(relationshipCardinality(erTables(diagram())[0]!, diagram().arrows[0]!)).toEqual({ child: '0..1', parent: '0..1' })
  expect(buildPostgresSQL(diagram())).toContain('REFERENCES "public"."staff" ("id")')
})

it('checks PG18 parameters, generation conflicts, candidate keys and malformed imported column references', () => {
  expect(typeError({ ...newColumn(), dataType: 'numeric', typeArgs: '2,-3' })).toBeUndefined()
  expect(typeError({ ...newColumn(), dataType: 'numeric', typeArgs: '3,5' })).toBeUndefined()
  expect(typeError({ ...newColumn(), dataType: 'numeric', typeArgs: '1001,2' })).toBeDefined()
  expect(formatDataType({ ...newColumn(), dataType: 'timestamp with time zone', typeArgs: '3', arrayDimensions: 2 })).toBe('timestamp(3) with time zone[][]')
  const { child, fk } = setup()
  store().saveERForeignKey(diagram().arrows[0]!.id, child.id, child.id, '', fk)
  // An incomplete referenced composite key must not pass as a valid single-column key.
  const arrow = diagram().arrows[0]!
  store().saveERForeignKey(arrow.id, arrow.source, arrow.target, arrow.label, { ...arrow.foreignKey!, columns: [fk.columns[0]!], referencedColumns: [fk.referencedColumns[0]!] })
  expect(validateER(diagram()).some(i => i.code === 'er-fk-key')).toBe(true)
  expect(() => buildPostgresSQL(diagram())).toThrow()
  const file = JSON.parse(serializeProject(store().project))
  file.diagrams[0].arrows[0].foreignKey.columns = ['missing-column']
  expect(() => parseProjectJson(JSON.stringify(file))).toThrow()
  expect(erTables(diagram())[0]!.height).toBe(tableHeight(erTables(diagram())[0]!))
})

it('exports PG18 generated columns, arrays, unique INCLUDE, partial indexes and escaped identifiers', () => {
  store().addERTable({ x: 0, y: 0 })
  const node = structuredClone(erTables(diagram())[0]!)
  node.table.schema = 'sales'
  const quantity = { ...newColumn('quantity'), dataType: 'integer', defaultValue: '1' }
  const price = { ...newColumn('price'), dataType: 'numeric', typeArgs: '12,2' }
  const code = { ...newColumn('code'), dataType: 'character varying', typeArgs: '128', collation: 'pg_catalog.C', comment: "O'Reilly \\ data" }
  node.table.columns.push(quantity, price, code,
    { ...newColumn('stored_total'), dataType: 'numeric', generated: 'STORED', expression: 'quantity * price' },
    { ...newColumn('virtual_total'), dataType: 'numeric', generated: 'VIRTUAL', expression: 'quantity * price' },
    { ...newColumn('times'), dataType: 'timestamp with time zone', typeArgs: '3', arrayDimensions: 1 },
    { ...newColumn('rounded'), dataType: 'numeric', typeArgs: '2,-3' })
  node.table.indexes.push({ id: 'uq-included', name: 'codes_unique', kind: 'unique', method: 'btree', unique: true, nullsNotDistinct: true, columns: [code.id], include: [price.id], predicate: '' },
    { id: 'idx-partial', name: 'positive_quantity', kind: 'index', method: 'btree', unique: true, nullsNotDistinct: true, columns: [quantity.id], include: [price.id], predicate: 'quantity > 0' })
  store().updateERTable(node.id, 'line"items', node.table, "Quoted ' table")
  const sql = buildPostgresSQL(diagram())
  expect(sql).toContain('"sales"."line""items"')
  expect(sql).toContain('GENERATED ALWAYS AS (quantity * price) VIRTUAL')
  expect(sql).toContain('timestamp(3) with time zone[]')
  expect(sql).toContain('UNIQUE NULLS NOT DISTINCT ("code") INCLUDE ("price")')
  expect(sql).toContain("E'O''Reilly \\\\ data'")
  if (process.env.ER_SQL_FIXTURE === '1') { mkdirSync('test-results', { recursive: true }); writeFileSync('test-results/pg18-features.sql', sql) }
  const invalid = structuredClone(erTables(diagram())[0]!)
  invalid.table.columns[0]!.defaultValue = '1'
  store().updateERTable(invalid.id, invalid.name, invalid.table, '')
  expect(validateER(diagram()).some(i => i.code === 'er-generation-conflict')).toBe(true)
})
