import type { EditorDiagram } from '@/types/diagram'
import { erTables, type ERTableNode } from './model'
import { formatDataType } from './postgresTypes'
import { validateER } from './validateER'

const q = (value: string) => `"${value.replaceAll('"', '""')}"`
const literal = (value: string) => `E'${value.replaceAll('\\', '\\\\').replaceAll("'", "''")}'`
const qualified = (node: ERTableNode) => `${q(node.table.schema)}.${q(node.name)}`
const names = (node: ERTableNode, ids: string[]) => ids.map(id => q(node.table.columns.find(c => c.id === id)!.name)).join(', ')
const constraint = (name: string) => name ? `CONSTRAINT ${q(name)} ` : ''

/** Generate a fresh schema; never execute SQL or destructive migrations. */
export function buildPostgresSQL(diagram: EditorDiagram): string {
  if (diagram.type !== 'er') throw new Error('Выберите ER-диаграмму.')
  const errors = validateER(diagram).filter(i => i.severity === 'error')
  if (errors.length) throw new Error(`Исправьте ошибки модели перед выгрузкой SQL: ${errors[0]!.message}`)
  const tables = erTables(diagram)
  const output = ['-- PostgreSQL 18 · Generated by Diagram Studio', '-- SQL expressions and operator classes must be checked on the target database.', 'BEGIN;']
  for (const schema of new Set(tables.map(t => t.table.schema))) output.push(`CREATE SCHEMA IF NOT EXISTS ${q(schema)};`)
  for (const n of tables) {
    const fields = n.table.columns.map(c => {
      let sql = `${q(c.name)} ${formatDataType(c)}`
      if (c.collation) sql += ` COLLATE ${c.collation.split('.').map(q).join('.')}`
      if (c.identity) sql += ` GENERATED ${c.identity} AS IDENTITY`
      if (c.generated) sql += ` GENERATED ALWAYS AS (${c.expression}) ${c.generated}`
      if (c.defaultValue.trim()) sql += ` DEFAULT ${c.defaultValue}`
      if (c.primaryKey || !c.nullable) sql += ' NOT NULL'
      if (c.unique) sql += ' UNIQUE'
      return sql
    })
    const pk = n.table.columns.filter(c => c.primaryKey).map(c => c.id)
    if (pk.length) fields.push(`PRIMARY KEY (${names(n, pk)})`)
    for (const i of n.table.indexes.filter(i => i.kind === 'unique')) fields.push(`${constraint(i.name)}UNIQUE${i.nullsNotDistinct ? ' NULLS NOT DISTINCT' : ''} (${names(n, i.columns)})${i.include.length ? ` INCLUDE (${names(n, i.include)})` : ''}`)
    for (const check of n.table.checks) fields.push(`${constraint(check.name)}CHECK (${check.expression})`)
    output.push(`CREATE ${n.table.unlogged ? 'UNLOGGED ' : ''}TABLE ${qualified(n)} (\n  ${fields.join(',\n  ')}\n);`)
    if (n.notes) output.push(`COMMENT ON TABLE ${qualified(n)} IS ${literal(n.notes)};`)
    for (const c of n.table.columns) if (c.comment) output.push(`COMMENT ON COLUMN ${qualified(n)}.${q(c.name)} IS ${literal(c.comment)};`)
  }
  // Unique indexes must exist before FKs that reference them. Cyclic FKs are valid.
  for (const n of tables) for (const i of n.table.indexes.filter(i => i.kind === 'index')) output.push(
    `CREATE ${i.unique ? 'UNIQUE ' : ''}INDEX ${i.name ? q(i.name) + ' ' : ''}ON ${qualified(n)} USING ${i.method} (${names(n, i.columns)})${i.include.length ? ` INCLUDE (${names(n, i.include)})` : ''}${i.nullsNotDistinct ? ' NULLS NOT DISTINCT' : ''}${i.predicate.trim() ? ` WHERE ${i.predicate}` : ''};`)
  for (const a of diagram.arrows) {
    const s = tables.find(n => n.id === a.source)!, t = tables.find(n => n.id === a.target)!, fk = a.foreignKey!
    output.push(`ALTER TABLE ${qualified(s)} ADD ${constraint(a.label)}FOREIGN KEY (${names(s, fk.columns)}) REFERENCES ${qualified(t)} (${names(t, fk.referencedColumns)}) MATCH ${fk.match} ON DELETE ${fk.onDelete} ON UPDATE ${fk.onUpdate}${fk.deferrable ? ` DEFERRABLE INITIALLY ${fk.initiallyDeferred ? 'DEFERRED' : 'IMMEDIATE'}` : ' NOT DEFERRABLE'};`)
  }
  output.push('COMMIT;')
  return output.join('\n\n') + '\n'
}
